# Generated by Django 2.0 on 2018-01-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('desc', models.TextField(null=True)),
                ('creatorId', models.BigIntegerField()),
                ('createdTime', models.DateTimeField()),
            ],
        ),
    ]
